In [1]:
!pip install transformers

In [2]:
from transformers import BertModel,BertTokenizer

In [3]:
model=BertModel.from_pretrained('bert-base-uncased')

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [4]:
dir(model)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adjust_bias',
 '_adjust_missing_and_unexpected_keys',
 '_apply',
 '_auto_class',
 '_backward_compatibility_gradient_checkpointing',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_can_compile_fullgraph',
 '_can_record_outputs',
 '_can_set_attn_implementation',
 '_can_set_experts_implementation',
 '_check_and_adjust_attn_implementation',
 '_check_and_adjust_experts_implementation',
 '_checkpoint_conversion_mapping',
 '_compiled_call_impl',
 '_copy_lm_head_original_to_resized',
 '_create_attentio

In [5]:
model.base_model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

In [6]:
 model.embeddings

BertEmbeddings(
  (word_embeddings): Embedding(30522, 768, padding_idx=0)
  (position_embeddings): Embedding(512, 768)
  (token_type_embeddings): Embedding(2, 768)
  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

In [7]:
model.encoder

BertEncoder(
  (layer): ModuleList(
    (0-11): 12 x BertLayer(
      (attention): BertAttention(
        (self): BertSelfAttention(
          (query): Linear(in_features=768, out_features=768, bias=True)
          (key): Linear(in_features=768, out_features=768, bias=True)
          (value): Linear(in_features=768, out_features=768, bias=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (output): BertSelfOutput(
          (dense): Linear(in_features=768, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (intermediate): BertIntermediate(
        (dense): Linear(in_features=768, out_features=3072, bias=True)
        (intermediate_act_fn): GELUActivation()
      )
      (output): BertOutput(
        (dense): Linear(in_features=3072, out_features=768, bias=True)
        (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)

In [10]:
model.parameters()

<generator object Module.parameters at 0x7906e1797d80>

BERT Tokenizer

In [11]:
sentence='we are learning bert embeddings'

In [12]:
tokenizer=BertTokenizer.from_pretrained('bert-base-uncased')
tokenizer

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

BertTokenizer(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [13]:
tokenizer.vocab.keys()

dict_keys(['ut', 'mackay', '##rro', 'deter', 'passports', 'viscount', 'ronald', 'crook', 'inflation', 'adjusting', 'appleton', 'herring', 'baggage', 'unlikely', 'pierce', '1906', 'vera', 'cedric', '##rvis', 'buzzed', '##koto', 'bouquet', 'martian', 'charitable', 'measurement', 'baja', 'vitamin', 'choke', 'cream', 'comes', 'workplace', 'offshore', 'components', '41st', 'banished', 'parchment', 'fisted', 'rebound', 'disgust', '##lices', 'snapping', 'amour', 'luisa', 'mario', 'radiating', 'charlton', 'gradual', 'deploy', '##ori', 'borrowing', 'midnight', 'mckenzie', 'replaces', 'cites', 'ever', 'stalking', 'asher', '##tsk', 'rave', '##apes', '##lists', 'studying', 'gently', 'paradise', 'playing', '##nger', 'sim', 'overlap', 'deacon', 'robb', '##note', 'validity', '##yuan', 'efficiency', 'provincial', 'associations', 'ج', 'sera', 'malik', '##400', 'র', 'stories', '[unused377]', 'wakefield', 'sired', '256', 'cote', 'sci', 'tobago', 'sorry', 'energy', 'whore', 'websites', 'disputed', 'offere

In [15]:
tokenizer.vocab['hello']

7592

In [17]:
 tokens=tokenizer.tokenize(sentence)
 tokens

['we', 'are', 'learning', 'bert', 'em', '##bed', '##ding', '##s']

In [18]:
tokenizer.vocab['##bed'],tokenizer.vocab['bed']

(8270, 2793)

In [20]:
tokens=tokenizer.tokenize('Machinelearning')
tokens

['machine', '##lea', '##rn', '##ing']

In [21]:
 tokens1=['[CLS]']+tokens+['[SEP]']
 tokens1

['[CLS]', 'machine', '##lea', '##rn', '##ing', '[SEP]']

In [22]:
tokens2=['[CLS]']+tokens+['[SEP]']+['[PAD]']+['[PAD]']
tokens2

['[CLS]', 'machine', '##lea', '##rn', '##ing', '[SEP]', '[PAD]', '[PAD]']

In [23]:
 attention_mask=[1 if i!='[PAD]' else 0 for i in tokens2]
 attention_mask

[1, 1, 1, 1, 1, 1, 0, 0]

Get Token Ids

In [24]:
 token_ids=tokenizer.convert_tokens_to_ids(tokens2)
 token_ids

[101, 3698, 19738, 6826, 2075, 102, 0, 0]

In [25]:
tokenizer.convert_tokens_to_string(tokens2)

'[CLS] machinelearning [SEP] [PAD] [PAD]'

In [26]:
tokenizer.convert_ids_to_tokens(token_ids)

['[CLS]', 'machine', '##lea', '##rn', '##ing', '[SEP]', '[PAD]', '[PAD]']

In [27]:
import torch
ids=torch.tensor(token_ids).unsqueeze(0)
mask=torch.tensor(attention_mask).unsqueeze(0)
ids,mask

(tensor([[  101,  3698, 19738,  6826,  2075,   102,     0,     0]]),
 tensor([[1, 1, 1, 1, 1, 1, 0, 0]]))

In [28]:
out=model(ids,attention_mask=mask)
dir(out)

['__annotations__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__dataclass_fields__',
 '__dataclass_params__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__match_args__',
 '__module__',
 '__ne__',
 '__new__',
 '__or__',
 '__post_init__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'attentions',
 'clear',
 'copy',
 'cross_attentions',
 'fromkeys',
 'get',
 'hidden_states',
 'items',
 'keys',
 'last_hidden_state',
 'move_to_end',
 'past_key_values',
 'pooler_output',
 'pop',
 'popitem',
 'setdefault',
 'to_tuple',
 'update',
 'values']

In [29]:
out.last_hidden_state.shape

torch.Size([1, 8, 768])

In [30]:
 out.pooler_output.shape

torch.Size([1, 768])

In [31]:
out[0]

tensor([[[ 0.0522,  0.1342,  0.0700,  ..., -0.2377,  0.1559,  0.1277],
         [ 0.7343,  0.0615, -0.0862,  ..., -0.7535,  0.0303,  0.1026],
         [ 1.0072,  0.2481,  0.6375,  ...,  0.1220,  0.0894, -1.7695],
         ...,
         [ 0.7361,  0.0268, -0.2873,  ...,  0.0535, -0.7832, -0.2563],
         [ 0.1460, -0.3650,  0.3289,  ..., -0.1841, -0.1731,  0.2239],
         [ 0.0872, -0.4578,  0.0965,  ..., -0.1603,  0.0205,  0.0894]]],
       grad_fn=<NativeLayerNormBackward0>)

In [32]:
out[1]

tensor([[-0.7995, -0.2531,  0.1245,  0.6221, -0.1931, -0.1242,  0.8226,  0.1744,
          0.2275, -0.9997,  0.0914,  0.2339,  0.9650, -0.1159,  0.8690, -0.3854,
         -0.0638, -0.4730,  0.3269, -0.5918,  0.5609,  0.9346,  0.4465,  0.2275,
          0.3531,  0.2159, -0.4540,  0.8848,  0.9108,  0.6779, -0.6323,  0.2519,
         -0.9689, -0.1820,  0.2001, -0.9695,  0.2366, -0.7183,  0.0688, -0.0205,
         -0.8237,  0.2572,  0.9942, -0.3383,  0.0219, -0.2911, -0.9996,  0.1623,
         -0.7954, -0.2914, -0.2061, -0.5150,  0.1475,  0.3453,  0.2952,  0.1875,
         -0.1331,  0.1276, -0.1204, -0.4908, -0.5043,  0.3249,  0.0286, -0.8226,
         -0.2749, -0.4279, -0.1124, -0.2789, -0.0354, -0.0162,  0.7280,  0.1567,
          0.2432, -0.7183, -0.3758,  0.1760, -0.3029,  1.0000, -0.3617, -0.9500,
         -0.2822, -0.1875,  0.2592,  0.4765, -0.3674, -1.0000,  0.2973, -0.1284,
         -0.9760,  0.2224,  0.3112, -0.1134, -0.4069,  0.2411, -0.2136, -0.1378,
         -0.1894,  0.3977, -

In [33]:
out[1][0][:10]

tensor([-0.7995, -0.2531,  0.1245,  0.6221, -0.1931, -0.1242,  0.8226,  0.1744,
         0.2275, -0.9997], grad_fn=<SliceBackward0>)