In [2]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
sentences=['sky is nice','sky is blue','sky is beautiful']

cleaned_sentence=[]

for sentence in sentences:
  word=sentence.lower()

  word=word.split()

  word=[i for i in word if i not in stopwords.words('english')]
  word=" ".join(word)
  cleaned_sentence.append(word)

print(cleaned_sentence)

['sky nice', 'sky blue', 'sky beautiful']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [4]:
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=3)
Bagofwords=cv.fit_transform(cleaned_sentence).toarray()
print(Bagofwords)

[[0 0 1]
 [0 1 1]
 [1 0 1]]


In [5]:
cv.vocabulary_

{'sky': np.int64(2), 'blue': np.int64(1), 'beautiful': np.int64(0)}